features:
  maxGames:
    description: Max number of games to play
    expression: userContext['gamesPlayed'] < planContext['maxGames']
    serverExpression: userContext['gamesPlayed'] <= planContext['maxGames']
    type: NUMERIC
    defaultValue: 0
  allowGameSpectators:
    description: Allow spectators in chess games
    expression: planContext['allowGameSpectators']
    type: CONDITION
    defaultValue: false
plans:
  BASIC:
    description: Plan for basic users
    price: 0.00
    currency: EUR
    features:
      maxGames:
        value: 2
      allowGameSpectators:
        value: false
  ADVANCED:
    description: Plan for advanced users
    price: 9.99
    currency: EUR
    features:
      maxGames:
        value: 25
      allowGameSpectators:
        value: true
  PRO:
    description: Plan for pro users
    price: 14.99
    currency: EUR
    features:
      maxGames:
        value: 100
      allowGameSpectators:
        value: true
